### ISSUE TITLE
Monokai dark soda and extract

### ISSUE THREAD

**Issue by kavillock** [rainje/Monokai-Dark-Soda#2]
based on https://github.com/rainje/Monokai-Dark-Soda/commit/d6562374eac3e3b8204b0db3c10cc6f8893bf28b#commitcomment-9712930

when i open psd file from extract, color sheme was changed to darker
http://imgur.com/a/Cp3yB

look for "div" keyword and other syntax hightlight, (i use color picker, so it cannot be idealy)
without extract: FF0B4E
with extract FF007F

**Comment by rainje** [comment]
God it took me a while to understand the issue. So, the colors scheme gets darker when you open a file in extract, I now see. But I don't think it's a theme related issue but rather an extension related issue. You can see the same thing happens when you use the default brackets dark theme, it gets darker when you use extract. I guess it'll be the same for every other theme. I checked if I could find a css property that change the color when loading a file but i wasn't able to find one. Sorry I think I can't do anything here.
